### ISSUE TITLE
Add capability to format as new writable card

### ISSUE THREAD

**Issue by Dinsmoor** [mofosyne/NFCMessageBoard#2]
Should be able to just use writeNdefMessage() just using a space Here:

https://developer.android.com/reference/android/nfc/tech/Ndef.html#writeNdefMessage(android.nfc.NdefMessage)

**Comment by mofosyne** [comment]
Just using a space? Or is this a replacement to having to setup a listener
thread?

**Comment by Dinsmoor** [comment]
A replacement to having the user use a different application to create a NDEF compliant writing slate, because those other apps put their app name in the NDEF field, causing it to open the associated NFC application that I put a space with, instead of writing to the card.

**Comment by mofosyne** [comment]
I wasn't able to get the time to totally rewrite the mess of a code that I got to adopt your more nicer suggestion.

But I did update the program code to allow for what you wanted anyway, of creating a new tag (As well as static header text, tagID display, tag restore, etc...) for V2.0

I think once that issue is sorted, that should be the end of my contribution to this codebase. Anything further is going to need a total rewrite lol.

But I hope that sorts out most of your issues. In time at least for whatever you were going to do with it :D

**Comment by Dinsmoor** [comment]
Thanks man, I can't wait for the build to be pushed to F-Droid. Keep up the good work!
Often I find that its beneficial to rewrite old projects, its sort of like drawing a piece of art better and better every time you try.

**Comment by mofosyne** [comment]
Good point. BTW do I need to do anything to update the fdroid appstore...

Or is that automatic via source?

**Comment by Dinsmoor** [comment]
I am pretty sure it's automatically retrieved by the f-droid servers.
However, here's some information that may help: https://f-droid.org/manual/fdroid.html#Metadata
And also it's here on f-droid: https://f-droid.org/repository/browse/?fdid=com.briankhuu.nfcmessageboard

Not sure. Guess we'll have to wait a few days and see.

Also I looked at your commit, and it didn't seem too terrible a mess. I'm more of a python guy myself, so I wouldn't have comparable java to compare with.

**Comment by mofosyne** [comment]
fair enough. Well the other things I was sorta thinking about, is that it would be nice if we can have a website so people can upload message tags they found (with gps coordinates) and browse a map of NFC messages (maybe with a way of seeing archived messages, even after the NFC tag is lost or destroyed). But I won't be constructing such site. Though if you are up for it, I can add some uploading capability into the app.

**Comment by Dinsmoor** [comment]
Go ahead and send me an email at pappad@airmail.cc and we can talk about it.

I've just started with Django, and it would be a good project.
I'd imagine the project would end up as a fork of an existing OpenStreetMap plugin that uses geocaching, and add location services to the application. Maybe.
